### ISSUE TITLE
User e-mail in create certificate not updated to new e-mail (+other issues)

### ISSUE THREAD

**Issue by Fabio-RibeiroB** [bradymd/django-certiffy#3]
I change my e-mail but still getting default in create cert.
Also, may be worth adding 127.0.0.1 in allowed hosts and git clone via ssh to https instead.

**Comment by Fabio-RibeiroB** [comment]
For some reason, my graph daystogo axis is reversed. Strange

**Comment by bradymd** [comment]
Thanks for testing deployment.
The 127.0.0.1 is done (easy).
The depoy.sh edited to git clone.
The model.py for certificates, I've removed the default contact which as you pointed out was me !
The graph .. will need me to study. Seems to work when a larger number of items are in so there is a real problem there.

**Comment by bradymd** [comment]
Hi Fabio.  The graph I have worked out what was happening. I've improved it on my test set but clearly I need to test it more. If you "get pull" and run again, tell me what you see. Hopefully better.
